/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.elka;

import java.io.IOException;
import java.net.URL;
import javafx.application.Application;
import static javafx.application.Application.launch;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import pw.elka.controllers.FXMLGuiController;

public class App extends Application{

    private FXMLGuiController guiController;
    public static void main(String[] args) {
        
        launch(args);
    }
  
    @Override
    public void start(Stage primaryStage) throws IOException { 
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/fxml/FXMLGui.fxml"));
        Parent root = loader.load();
        guiController = loader.getController();
        Scene scene = new Scene(root);
        primaryStage.setTitle("TK simulator");
        primaryStage.setScene(scene);
        primaryStage.show();
        System.out.println("Application ver 0.1\nAuthors: Jan Jakubik & Oskar Misiewicz");
        // Tutaj już nic nie pisz, pisz w FXMLGuiController :)
    }

    
}
